steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/boxwood-bliss-375813/awesome-project:$SHORT_SHA', '.' ]
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/boxwood-bliss-375813/awesome-project:$SHORT_SHA' ]
          
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy',  'awesome-project', '--region=asia-south1', '--platform=managed', '--image=gcr.io/boxwood-bliss-375813/awesome-project:$SHORT_SHA' ]

